#ifndef _GRAPHICSCOMMANDS_H_
#define _GRAPHICSCOMMANDS_H_

#include "TypesC.h"

#define PF_GRAPHICS_CMD_SETRENDERTARGET				EBYTENO_1
#define PF_GRAPHICS_CMD_SETSHADER					EBYTENO_2		
#define PF_GRAPHICS_CMD_SETVERTEXBUFFER				EBYTENO_3
#define PF_GRAPHICS_CMD_SETINDEXBUFFER				EBYTENO_4

#endif