//****************************************************************************************************/
//
//	Filename : Float32_4.h
//
//	Descritpion : 4 dimension vector of 32bit floats
//
//
//****************************************************************************************************/

#ifndef __PRAGMAONCE_PARABELLUMUTILS_FLOAT32_4_H__
#define __PRAGMAONCE_PARABELLUMUTILS_FLOAT32_4_H__

#include "Configuration.h"
#include "Fixes.h"
#include "Types.h"
#include "Accessor.h"

#include "Float32_2.h"
#include "Float32_3.h"





namespace ParabellumUtils
{

	// 4 dimension vector of 32bit floats
	class Float32_4
	{

	//
	//	Data
	//
	public:

		union
		{
			struct
			{
				EFLOAT32 X;
				EFLOAT32 Y;
				EFLOAT32 Z;
				EFLOAT32 W;
			};

			#ifdef PARABELLUMUTILS_CONFIGURATION_SSE
			struct
			{
				__m128 m128;
			};
			#endif

			// 16 Bytes variable - for shaders parametrs purpose
			struct
			{
				EFLOAT32 data[4];
			} DATA;

			
			struct
			{
				Float32_3 XYZ;
				EFLOAT32 W;
			};

			struct
			{
				EFLOAT32 X;
				Float32_3 YZW;
			};

			struct
			{
				Float32_2 XY;
				Float32_2 ZW;
			};

			struct
			{
				Float32_2 C0;
				Float32_2 C1;
			};

		};


		//
		//	Constructors and destructors
		//
		public:

			Float32_4()
			{
			}

			Float32_4(EFLOAT32 x, EFLOAT32 y, EFLOAT32 z, EFLOAT32 w)
			{
				X = x;
				Y = y;
				Z = z;
				W = w;
			}


		//
		// Operators
		//
		public:

			Float32_4& operator=(Float32_4& rhs)
			{
				this->X = rhs.X;
				this->Y = rhs.Y;
				this->Z = rhs.Z;

				return *this;
			}



		//
		// Accessors
		// 
		public:


			PU_ACCESSOR_2_DECLARE(EFLOAT32, 2, XX, X, X)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, XXX, X, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XXXX, X, X, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XXXY, X, X, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XXXZ, X, X, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XXXW, X, X, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, XXY, X, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XXYX, X, X, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XXYY, X, X, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XXYZ, X, X, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XXYW, X, X, Y, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, XXZ, X, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XXZX, X, X, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XXZY, X, X, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XXZZ, X, X, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XXZW, X, X, Z, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, XXW, X, X, W)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XXWX, X, X, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XXWY, X, X, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XXWZ, X, X, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XXWW, X, X, W, W)
			//PU_ACCESSOR_2_DECLARE(EFLOAT32, 2, XY, X, Y)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, XYX, X, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XYXX, X, Y, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XYXY, X, Y, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XYXZ, X, Y, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XYXW, X, Y, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, XYY, X, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XYYX, X, Y, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XYYY, X, Y, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XYYZ, X, Y, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XYYW, X, Y, Y, W)
			//PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, XYZ, X, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XYZX, X, Y, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XYZY, X, Y, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XYZZ, X, Y, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XYZW, X, Y, Z, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, XYW, X, Y, W)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XYWX, X, Y, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XYWY, X, Y, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XYWZ, X, Y, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XYWW, X, Y, W, W)
			PU_ACCESSOR_2_DECLARE(EFLOAT32, 2, XZ, X, Z)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, XZX, X, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XZXX, X, Z, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XZXY, X, Z, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XZXZ, X, Z, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XZXW, X, Z, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, XZY, X, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XZYX, X, Z, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XZYY, X, Z, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XZYZ, X, Z, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XZYW, X, Z, Y, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, XZZ, X, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XZZX, X, Z, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XZZY, X, Z, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XZZZ, X, Z, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XZZW, X, Z, Z, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, XZW, X, Z, W)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XZWX, X, Z, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XZWY, X, Z, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XZWZ, X, Z, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XZWW, X, Z, W, W)
			PU_ACCESSOR_2_DECLARE(EFLOAT32, 2, XW, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, XWX, X, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XWXX, X, W, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XWXY, X, W, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XWXZ, X, W, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XWXW, X, W, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, XWY, X, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XWYX, X, W, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XWYY, X, W, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XWYZ, X, W, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XWYW, X, W, Y, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, XWZ, X, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XWZX, X, W, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XWZY, X, W, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XWZZ, X, W, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XWZW, X, W, Z, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, XWW, X, W, W)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XWWX, X, W, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XWWY, X, W, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XWWZ, X, W, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, XWWW, X, W, W, W)
			PU_ACCESSOR_2_DECLARE(EFLOAT32, 2, YX, Y, X)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, YXX, Y, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YXXX, Y, X, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YXXY, Y, X, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YXXZ, Y, X, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YXXW, Y, X, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, YXY, Y, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YXYX, Y, X, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YXYY, Y, X, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YXYZ, Y, X, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YXYW, Y, X, Y, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, YXZ, Y, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YXZX, Y, X, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YXZY, Y, X, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YXZZ, Y, X, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YXZW, Y, X, Z, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, YXW, Y, X, W)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YXWX, Y, X, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YXWY, Y, X, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YXWZ, Y, X, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YXWW, Y, X, W, W)
			PU_ACCESSOR_2_DECLARE(EFLOAT32, 2, YY, Y, Y)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, YYX, Y, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YYXX, Y, Y, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YYXY, Y, Y, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YYXZ, Y, Y, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YYXW, Y, Y, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, YYY, Y, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YYYX, Y, Y, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YYYY, Y, Y, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YYYZ, Y, Y, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YYYW, Y, Y, Y, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, YYZ, Y, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YYZX, Y, Y, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YYZY, Y, Y, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YYZZ, Y, Y, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YYZW, Y, Y, Z, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, YYW, Y, Y, W)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YYWX, Y, Y, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YYWY, Y, Y, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YYWZ, Y, Y, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YYWW, Y, Y, W, W)
			PU_ACCESSOR_2_DECLARE(EFLOAT32, 2, YZ, Y, Z)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, YZX, Y, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YZXX, Y, Z, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YZXY, Y, Z, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YZXZ, Y, Z, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YZXW, Y, Z, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, YZY, Y, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YZYX, Y, Z, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YZYY, Y, Z, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YZYZ, Y, Z, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YZYW, Y, Z, Y, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, YZZ, Y, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YZZX, Y, Z, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YZZY, Y, Z, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YZZZ, Y, Z, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YZZW, Y, Z, Z, W)
			//PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, YZW, Y, Z, W)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YZWX, Y, Z, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YZWY, Y, Z, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YZWZ, Y, Z, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YZWW, Y, Z, W, W)
			PU_ACCESSOR_2_DECLARE(EFLOAT32, 2, YW, Y, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, YWX, Y, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YWXX, Y, W, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YWXY, Y, W, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YWXZ, Y, W, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YWXW, Y, W, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, YWY, Y, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YWYX, Y, W, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YWYY, Y, W, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YWYZ, Y, W, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YWYW, Y, W, Y, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, YWZ, Y, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YWZX, Y, W, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YWZY, Y, W, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YWZZ, Y, W, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YWZW, Y, W, Z, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, YWW, Y, W, W)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YWWX, Y, W, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YWWY, Y, W, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YWWZ, Y, W, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, YWWW, Y, W, W, W)
			PU_ACCESSOR_2_DECLARE(EFLOAT32, 2, ZX, Z, X)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, ZXX, Z, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZXXX, Z, X, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZXXY, Z, X, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZXXZ, Z, X, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZXXW, Z, X, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, ZXY, Z, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZXYX, Z, X, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZXYY, Z, X, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZXYZ, Z, X, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZXYW, Z, X, Y, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, ZXZ, Z, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZXZX, Z, X, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZXZY, Z, X, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZXZZ, Z, X, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZXZW, Z, X, Z, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, ZXW, Z, X, W)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZXWX, Z, X, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZXWY, Z, X, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZXWZ, Z, X, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZXWW, Z, X, W, W)
			PU_ACCESSOR_2_DECLARE(EFLOAT32, 2, ZY, Z, Y)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, ZYX, Z, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZYXX, Z, Y, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZYXY, Z, Y, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZYXZ, Z, Y, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZYXW, Z, Y, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, ZYY, Z, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZYYX, Z, Y, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZYYY, Z, Y, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZYYZ, Z, Y, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZYYW, Z, Y, Y, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, ZYZ, Z, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZYZX, Z, Y, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZYZY, Z, Y, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZYZZ, Z, Y, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZYZW, Z, Y, Z, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, ZYW, Z, Y, W)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZYWX, Z, Y, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZYWY, Z, Y, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZYWZ, Z, Y, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZYWW, Z, Y, W, W)
			PU_ACCESSOR_2_DECLARE(EFLOAT32, 2, ZZ, Z, Z)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, ZZX, Z, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZZXX, Z, Z, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZZXY, Z, Z, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZZXZ, Z, Z, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZZXW, Z, Z, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, ZZY, Z, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZZYX, Z, Z, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZZYY, Z, Z, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZZYZ, Z, Z, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZZYW, Z, Z, Y, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, ZZZ, Z, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZZZX, Z, Z, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZZZY, Z, Z, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZZZZ, Z, Z, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZZZW, Z, Z, Z, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, ZZW, Z, Z, W)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZZWX, Z, Z, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZZWY, Z, Z, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZZWZ, Z, Z, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZZWW, Z, Z, W, W)
			//PU_ACCESSOR_2_DECLARE(EFLOAT32, 2, ZW, Z, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, ZWX, Z, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZWXX, Z, W, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZWXY, Z, W, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZWXZ, Z, W, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZWXW, Z, W, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, ZWY, Z, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZWYX, Z, W, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZWYY, Z, W, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZWYZ, Z, W, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZWYW, Z, W, Y, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, ZWZ, Z, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZWZX, Z, W, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZWZY, Z, W, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZWZZ, Z, W, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZWZW, Z, W, Z, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, ZWW, Z, W, W)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZWWX, Z, W, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZWWY, Z, W, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZWWZ, Z, W, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, ZWWW, Z, W, W, W)
			PU_ACCESSOR_2_DECLARE(EFLOAT32, 2, WX, W, X)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, WXX, W, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WXXX, W, X, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WXXY, W, X, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WXXZ, W, X, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WXXW, W, X, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, WXY, W, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WXYX, W, X, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WXYY, W, X, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WXYZ, W, X, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WXYW, W, X, Y, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, WXZ, W, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WXZX, W, X, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WXZY, W, X, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WXZZ, W, X, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WXZW, W, X, Z, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, WXW, W, X, W)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WXWX, W, X, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WXWY, W, X, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WXWZ, W, X, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WXWW, W, X, W, W)
			PU_ACCESSOR_2_DECLARE(EFLOAT32, 2, WY, W, Y)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, WYX, W, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WYXX, W, Y, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WYXY, W, Y, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WYXZ, W, Y, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WYXW, W, Y, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, WYY, W, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WYYX, W, Y, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WYYY, W, Y, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WYYZ, W, Y, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WYYW, W, Y, Y, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, WYZ, W, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WYZX, W, Y, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WYZY, W, Y, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WYZZ, W, Y, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WYZW, W, Y, Z, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, WYW, W, Y, W)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WYWX, W, Y, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WYWY, W, Y, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WYWZ, W, Y, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WYWW, W, Y, W, W)
			PU_ACCESSOR_2_DECLARE(EFLOAT32, 2, WZ, W, Z)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, WZX, W, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WZXX, W, Z, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WZXY, W, Z, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WZXZ, W, Z, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WZXW, W, Z, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, WZY, W, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WZYX, W, Z, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WZYY, W, Z, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WZYZ, W, Z, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WZYW, W, Z, Y, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, WZZ, W, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WZZX, W, Z, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WZZY, W, Z, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WZZZ, W, Z, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WZZW, W, Z, Z, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, WZW, W, Z, W)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WZWX, W, Z, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WZWY, W, Z, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WZWZ, W, Z, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WZWW, W, Z, W, W)
			PU_ACCESSOR_2_DECLARE(EFLOAT32, 2, WW, W, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, WWX, W, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WWXX, W, W, X, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WWXY, W, W, X, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WWXZ, W, W, X, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WWXW, W, W, X, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, WWY, W, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WWYX, W, W, Y, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WWYY, W, W, Y, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WWYZ, W, W, Y, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WWYW, W, W, Y, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, WWZ, W, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WWZX, W, W, Z, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WWZY, W, W, Z, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WWZZ, W, W, Z, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WWZW, W, W, Z, W)
			PU_ACCESSOR_3_DECLARE(EFLOAT32, 3, WWW, W, W, W)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WWWX, W, W, W, X)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WWWY, W, W, W, Y)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WWWZ, W, W, W, Z)
			PU_ACCESSOR_4_DECLARE(EFLOAT32, 4, WWWW, W, W, W, W)

	};





}



#endif